#!/bin/sh
if ! find . -mindepth 1 | read; then
  echo -e "Creating default configs...\n"
  cp -r /opt/cfx-server-data/* /config
fi

if [ -z "${RCON_PASSWORD}" ]; then
  echo "RCON_PASSWORD key not found in environment."
  exit 1
fi

sed -e "s/{RCON_PASS}/${RCON_PASSWORD}/g" /server.cfg > /config/server.cfg;
echo "----------------------------------------------"
echo "Your RCON password is set to: ${RCON_PASSWORD}"
echo -e "----------------------------------------------\n"


if [ -z "${LICENSE_KEY}" ]; then
  echo "License key not found in environment, please create one at https://keymaster.fivem.net!"
  exit 1
fi


exec /opt/cfx-server/FXServer \
       +set citizen_dir /opt/cfx-server/citizen/ \
       +exec /config/server.cfg $@ \
       +set sv_licenseKey ${LICENSE_KEY}

